### ISSUE TITLE
Pinned posts

### ISSUE THREAD

**Issue by MarceauKa** [MarceauKa/laravel-shaarli#11]
Can pin posts to be displayed first

**Comment by papapkis** [comment]
Hi, can i work on this issue ? :)

**Comment by MarceauKa** [comment]
Yep of course! Please work on an other branch than `master` and if you can try to add tests.

**Comment by MarceauKa** [comment]
Released in [1.2.21](https://github.com/MarceauKa/laravel-shaarli/releases/tag/1.2.21)
