### ISSUE TITLE
Suggestions

### ISSUE THREAD

**Issue by ArthurHoaro** [MarceauKa/laravel-shaarli#13]
It seems to be a solid project for such a short development time! :+1: 

If I may suggest a few improvements after a quick glance at the project: 

  * it seems to have a lot of dependencies, maybe necessary but undocumented (PHP Excel ?)
  * due to these dependencies, required PHP extensions should be added to the README 
  * you should explain how to get it started with SQLite as the default `.env` contains MySQL settings
  * almost no unit tests :eyes:

**Comment by MarceauKa** [comment]
Hi @ArthurHoaro and thank you for your feedback! I'll try to answer all your interrogations.

- I've tried to document all php and js dependencies [here](https://github.com/MarceauKa/laravel-shaarli/blob/dev/readme.md#dependencies)
- I don't think we need to suggest PHP extension, Laravel do this for us in its composer.json (no php extension required for excel)
- Additional documentation is now described [here](https://github.com/MarceauKa/laravel-shaarli/blob/dev/readme.md#additional-configuration)
- Yeah, I confess 👏(but no unit tests, only E2E tests)

**Comment by wyred** [comment]
I'm not familiar with node. I followed the installation instructions here (https://docs.aws.amazon.com/sdk-for-javascript/v2/developer-guide/setting-up-node-on-ec2-instance.html) and managed to get it installed, but I'm getting a permissions error.

```
[previous exception] [object] (Symfony\\Component\\Process\\Exception\\ProcessFailedException(code: 0): The command \"'/home/ec2-user/.nvm/versions/node/v12.11.1/bin/node' '/var/www/shaarli/vendor/nesk/rialto/src/node-process/serve.js' '/var/www/shaarli/vendor/nesk/puphpeteer/src/PuppeteerConnectionDelegate.js' '{\"idle_timeout\":60,\"log_node_console\":false,\"log_browser_console\":false}'\" failed.

Exit Code: 126(Invoked command cannot execute)

Working directory: /var/www/shaarli/public

Output:
================


Error Output:
================
sh: /home/ec2-user/.nvm/versions/node/v12.11.1/bin/node: Permission denied
sh: line 0: exec: /home/ec2-user/.nvm/versions/node/v12.11.1/bin/node: cannot execute: Permission denied
 at /var/www/shaarli/vendor/nesk/rialto/src/ProcessSupervisor.php:309)
```

Would you be able to share what your installation procedure is in order to get the "PDF Archiving" feature to work?

**Comment by MarceauKa** [comment]
Yeah, I experienced the same issue on CentOS.

I had to install some dependencies:
```bash
yum install ipa-gothic-fonts xorg-x11-fonts-100dpi xorg-x11-fonts-75dpi xorg-x11-utils xorg-x11-fonts-cyrillic xorg-x11-fonts-Type1 xorg-x11-fonts-misc -y
```
