### ISSUE TITLE
Manage menu not clickable on Safari

### ISSUE THREAD

**Issue by wyred** [MarceauKa/laravel-shaarli#18]
Hi,

Thanks for making this app!

I've just installed it on my server and have encountered a few problems. One of them is this menu.
It is not clickable on when viewed on Safari v13.0.1.
It works fine on google Chrome

![shaarli-manage-menu](https://user-images.githubusercontent.com/432325/66623662-4eb2e900-ec1f-11e9-9988-dd1d2d5882f3.png)

**Comment by MarceauKa** [comment]
Ah! Annoying 😅But strange because it's a simple bootstrap 4 menu.

**Comment by MarceauKa** [comment]
Fixed with more than one card
