### ISSUE TITLE
Extra HTML code in "Title" field when adding URL

### ISSUE THREAD

**Issue by wyred** [MarceauKa/laravel-shaarli#19]
At the "Add Link" form, I fill in the URL, the Title and Content is then auto-filled. However, the Title field has some extra HTML codes.

![shaarli-addurl](https://user-images.githubusercontent.com/432325/66812438-75498a80-ef65-11e9-8382-0796dd9f007b.png)

This is on v1.2.16

**Edit:** Looks like this happens only when there's a `/` in the title

**Comment by MarceauKa** [comment]
Ok, a patch will be released in the next release. The WebParser needs some improvements in the future.

**Comment by MarceauKa** [comment]
Released in [1.2.17](https://github.com/MarceauKa/laravel-shaarli/releases/tag/1.2.17), you'd be in love with the new `shaarli:update` command and the new dark mode 😊

**Comment by wyred** [comment]
Sorry to be so annoying, here's another small problem I found.

![htmlchars](https://user-images.githubusercontent.com/432325/66892494-712d7380-f01e-11e9-9a83-080e49fe1acc.png)

**Comment by MarceauKa** [comment]
The [WebParser](https://github.com/MarceauKa/laravel-shaarli/blob/master/app/Services/WebParser.php) component needs some refactoring. It'll use Symfony DomCrawler for better results. Feel free to make a PR :)

**Comment by MarceauKa** [comment]
Updated in [1.2.18](https://github.com/MarceauKa/laravel-shaarli/releases/tag/1.2.18)
