### ISSUE TITLE
Search does not work for Japanese text

### ISSUE THREAD

**Issue by wyred** [MarceauKa/laravel-shaarli#33]
On English, it works fine:
![スクリーンショット 2019-10-25 午後3 26 04](https://user-images.githubusercontent.com/432325/67551582-dd555900-f73b-11e9-82f5-ebd6a4f27670.png)

When searching Japanese, nothing shows up:
![スクリーンショット 2019-10-25 午後3 26 16](https://user-images.githubusercontent.com/432325/67551596-e6dec100-f73b-11e9-8748-3a99b7640c02.png)

Thought you might want to know in case you want to push this project to Japanese users.

**Comment by MarceauKa** [comment]
Thank you for your feedback!

**Comment by wyred** [comment]
Yes, but in Japanese text, there are no spaces between words.

**Comment by MarceauKa** [comment]
I know. I think a lot about that. The mysql scout engine actually used need spaces to build its words index. We also can configure the scout engine to use Algolia but it's a third party who store our data. I'm trying to implements a fallback to a simple SQL `LIKE %search%`

**Comment by MarceauKa** [comment]
Released in [1.2.29](https://github.com/MarceauKa/laravel-shaarli/releases/tag/1.2.29)
