### ISSUE TITLE
[Question] No need yarn at installation?

### ISSUE THREAD

**Issue by mzch** [MarceauKa/laravel-shaarli#35]
In readme.md Installation process doesn't include `yarn` or `npm run prod`.
Is there no need to exec them?

and

When setting `APP_ENV=production`, `php artisan shaarli:install` always fails. It it OK?

**Comment by MarceauKa** [comment]
Hi! Nope it's not needed, the build is provisionned in the repo. You'll just need to npm install if you want to archive links (as described in the readme).
Secondly, `shaarli:install` will not work in production. Install the app in local mode, then set it in production, then make a `composer install --no-dev`

**Comment by mzch** [comment]
All right. Thank you! :)
