### ISSUE TITLE
css and js broke

### ISSUE THREAD

**Issue by amanijoseph87** [MarceauKa/laravel-shaarli#40]
Hi, am testing shaarli but am getting an error in CSS and js broke. I think its something to do with a public folder or mix-manifest.json file is not readable.

![Laravel Shaarli - Laravel Shaarli - Google Chrome 11_5_2019 7_48_01 AM (2)](https://user-images.githubusercontent.com/21230918/68179470-0b8b3200-ffa1-11e9-95df-54f65f57a3a5.png)
 am using xamp

**Comment by MarceauKa** [comment]
Hi! Just tested a fresh install and no problem, are you using the master branch?

**Comment by amanijoseph87** [comment]
yes.

**Comment by amanijoseph87** [comment]
What can I do.. is there a way to remove the public folder and to add all asset on a root domain

**Comment by amanijoseph87** [comment]
and to be able to access the site i have to add public on url why is that

**Comment by MarceauKa** [comment]
You need to put the root on the `public/` folder. That's the way we configure a PHP project nowadays.
