### ISSUE TITLE
Find duplicates

### ISSUE THREAD

**Issue by MarceauKa** [MarceauKa/laravel-shaarli#9]
Check if a link is already shared when adding one

**Comment by fifkis** [comment]
Hi can i work on this issue ?

**Comment by MarceauKa** [comment]
Of course, look at the PR #16 made by @tuananhp-1844.

**Comment by MarceauKa** [comment]
Closed in [1.2.16](https://github.com/MarceauKa/laravel-shaarli/releases/tag/1.2.16)
